# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'diskdb.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1189, 600)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1176, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MainVLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MainVLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.MainVLayout.setContentsMargins(0, 0, 0, 6)
        self.MainVLayout.setObjectName("MainVLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBoxSELECT = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxSELECT.setEditable(True)
        self.comboBoxSELECT.setProperty("currentText", "")
        self.comboBoxSELECT.setObjectName("comboBoxSELECT")
        self.horizontalLayout.addWidget(self.comboBoxSELECT)
        self.comboBox_Distinct = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_Distinct.setEditable(True)
        self.comboBox_Distinct.setProperty("currentText", "DISTINCT")
        self.comboBox_Distinct.setObjectName("comboBox_Distinct")
        self.comboBox_Distinct.addItem("")
        self.comboBox_Distinct.addItem("")
        self.comboBox_Distinct.addItem("")
        self.comboBox_Distinct.setItemText(2, "")
        self.horizontalLayout.addWidget(self.comboBox_Distinct)
        self.comboBox_fields = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_fields.setEditable(True)
        self.comboBox_fields.setObjectName("comboBox_fields")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.comboBox_fields.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_fields)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_files = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_files.setEditable(True)
        self.comboBox_files.setObjectName("comboBox_files")
        self.comboBox_files.addItem("")
        self.comboBox_files.setItemText(0, "files")
        self.comboBox_files.addItem("")
        self.comboBox_files.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_files)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_Where = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_Where.setObjectName("lineEdit_Where")
        self.horizontalLayout.addWidget(self.lineEdit_Where)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox_group = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_group.setEditable(True)
        self.comboBox_group.setObjectName("comboBox_group")
        self.comboBox_group.addItem("")
        self.comboBox_group.setItemText(0, "")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.comboBox_group.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_group)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.having_condition = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.having_condition.setObjectName("having_condition")
        self.horizontalLayout.addWidget(self.having_condition)
        self.label_order = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_order.setObjectName("label_order")
        self.horizontalLayout.addWidget(self.label_order)
        self.comboBox_fields_order = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_fields_order.setEditable(True)
        self.comboBox_fields_order.setObjectName("comboBox_fields_order")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.setItemText(0, "")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.comboBox_fields_order.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_fields_order)
        self.execSelect = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.execSelect.setObjectName("execSelect")
        self.horizontalLayout.addWidget(self.execSelect)
        self.MainVLayout.addLayout(self.horizontalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1170, 513))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.selectResult = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents)
        self.selectResult.setGeometry(QtCore.QRect(-120, 30, 1421, 381))
        self.selectResult.setObjectName("selectResult")
        self.selectverticalScrollBar = QtWidgets.QScrollBar(self.scrollAreaWidgetContents)
        self.selectverticalScrollBar.setGeometry(QtCore.QRect(1150, 0, 16, 331))
        self.selectverticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.selectverticalScrollBar.setObjectName("selectverticalScrollBar")
        self.CheckCreateTable = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.CheckCreateTable.setGeometry(QtCore.QRect(50, 430, 141, 23))
        self.CheckCreateTable.setObjectName("CheckCreateTable")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setGeometry(QtCore.QRect(210, 430, 111, 32))
        self.lineEdit.setObjectName("lineEdit")
        self.progressBar = QtWidgets.QProgressBar(self.scrollAreaWidgetContents)
        self.progressBar.setGeometry(QtCore.QRect(10, 490, 1061, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.comboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox.setGeometry(QtCore.QRect(60, 460, 1061, 32))
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(0, 470, 58, 18))
        self.label_5.setObjectName("label_5")
        self.execSelect_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.execSelect_2.setGeometry(QtCore.QRect(1120, 460, 51, 34))
        self.execSelect_2.setObjectName("execSelect_2")
        self.selectResult.raise_()
        self.selectverticalScrollBar.raise_()
        self.CheckCreateTable.raise_()
        self.lineEdit.raise_()
        self.progressBar.raise_()
        self.comboBox.raise_()
        self.label_5.raise_()
        self.execSelect_2.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.MainVLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1189, 29))
        self.menubar.setObjectName("menubar")
        self.menuCreate_databasw = QtWidgets.QMenu(self.menubar)
        self.menuCreate_databasw.setObjectName("menuCreate_databasw")
        MainWindow.setMenuBar(self.menubar)
        self.actionCreate_database = QtWidgets.QAction(MainWindow)
        self.actionCreate_database.setObjectName("actionCreate_database")
        self.actionUpdate_database = QtWidgets.QAction(MainWindow)
        self.actionUpdate_database.setObjectName("actionUpdate_database")
        self.actionAnalyze = QtWidgets.QAction(MainWindow)
        self.actionAnalyze.setObjectName("actionAnalyze")
        self.menuCreate_databasw.addAction(self.actionCreate_database)
        self.menuCreate_databasw.addAction(self.actionUpdate_database)
        self.menuCreate_databasw.addAction(self.actionAnalyze)
        self.menubar.addAction(self.menuCreate_databasw.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Diskdb App"))
        self.comboBox_Distinct.setItemText(0, _translate("MainWindow", "DISTINCT"))
        self.comboBox_Distinct.setItemText(1, _translate("MainWindow", "ALL"))
        self.comboBox_fields.setItemText(0, _translate("MainWindow", "*"))
        self.comboBox_fields.setItemText(1, _translate("MainWindow", "fsroot"))
        self.comboBox_fields.setItemText(2, _translate("MainWindow", "ino"))
        self.comboBox_fields.setItemText(3, _translate("MainWindow", "dir"))
        self.comboBox_fields.setItemText(4, _translate("MainWindow", "filename"))
        self.comboBox_fields.setItemText(5, _translate("MainWindow", "type"))
        self.comboBox_fields.setItemText(6, _translate("MainWindow", "size"))
        self.comboBox_fields.setItemText(7, _translate("MainWindow", "mtime"))
        self.comboBox_fields.setItemText(8, _translate("MainWindow", "atime"))
        self.comboBox_fields.setItemText(9, _translate("MainWindow", "ctime"))
        self.comboBox_fields.setItemText(10, _translate("MainWindow", "uid"))
        self.comboBox_fields.setItemText(11, _translate("MainWindow", "gid"))
        self.label_4.setText(_translate("MainWindow", "FROM"))
        self.comboBox_files.setItemText(1, _translate("MainWindow", "dirs"))
        self.comboBox_files.setItemText(2, _translate("MainWindow", "files inner join dirs on files.dirid=dirs.rowid"))
        self.label.setText(_translate("MainWindow", "WHERE"))
        self.label_2.setText(_translate("MainWindow", "GROUP BY"))
        self.comboBox_group.setItemText(1, _translate("MainWindow", "*"))
        self.comboBox_group.setItemText(2, _translate("MainWindow", "fsroot"))
        self.comboBox_group.setItemText(3, _translate("MainWindow", "ino"))
        self.comboBox_group.setItemText(4, _translate("MainWindow", "dir"))
        self.comboBox_group.setItemText(5, _translate("MainWindow", "filename"))
        self.comboBox_group.setItemText(6, _translate("MainWindow", "type"))
        self.comboBox_group.setItemText(7, _translate("MainWindow", "size"))
        self.comboBox_group.setItemText(8, _translate("MainWindow", "mtime"))
        self.comboBox_group.setItemText(9, _translate("MainWindow", "atime"))
        self.comboBox_group.setItemText(10, _translate("MainWindow", "ctime"))
        self.comboBox_group.setItemText(11, _translate("MainWindow", "uid"))
        self.comboBox_group.setItemText(12, _translate("MainWindow", "gid"))
        self.label_3.setText(_translate("MainWindow", "HAVING"))
        self.label_order.setText(_translate("MainWindow", "ORDER BY"))
        self.comboBox_fields_order.setItemText(1, _translate("MainWindow", "*"))
        self.comboBox_fields_order.setItemText(2, _translate("MainWindow", "fsroot"))
        self.comboBox_fields_order.setItemText(3, _translate("MainWindow", "ino"))
        self.comboBox_fields_order.setItemText(4, _translate("MainWindow", "dir"))
        self.comboBox_fields_order.setItemText(5, _translate("MainWindow", "filename"))
        self.comboBox_fields_order.setItemText(6, _translate("MainWindow", "type"))
        self.comboBox_fields_order.setItemText(7, _translate("MainWindow", "size"))
        self.comboBox_fields_order.setItemText(8, _translate("MainWindow", "mtime"))
        self.comboBox_fields_order.setItemText(9, _translate("MainWindow", "atime"))
        self.comboBox_fields_order.setItemText(10, _translate("MainWindow", "ctime"))
        self.comboBox_fields_order.setItemText(11, _translate("MainWindow", "uid"))
        self.comboBox_fields_order.setItemText(12, _translate("MainWindow", "gid"))
        self.execSelect.setText(_translate("MainWindow", "Go!"))
        self.CheckCreateTable.setText(_translate("MainWindow", "Create view"))
        self.lineEdit.setText(_translate("MainWindow", "temp"))
        self.label_5.setText(_translate("MainWindow", "History"))
        self.execSelect_2.setText(_translate("MainWindow", "Go!"))
        self.menuCreate_databasw.setTitle(_translate("MainWindow", "&Menu"))
        self.actionCreate_database.setText(_translate("MainWindow", "&Create database"))
        self.actionUpdate_database.setText(_translate("MainWindow", "&Update database"))
        self.actionAnalyze.setText(_translate("MainWindow", "&Analyze"))

from . import diskdb_rc
